// YAL zeldan

#ifndef CXU_MYMACROS
#define CXU_MYMACROS


#define LOOP CXU_LOOP
#define LOOPX CXU_LOOPX

#define DIM CXU_DIM
#define ZERO CXU_ZERO

#define XVAR CXU_XVAR
#define CAT CXU_CAT

//#define throwCXUEXCEPTION CXU_throwCXUEXCEPTION
//#define logCXUEXCEPTION CXU_logCXUEXCEPTION

#define assertDBG CXU_assertDBG



#define THROWEXCEPTION CXU_THROWEXCEPTION
#define LOGEXCEPTION CXU_LOGEXCEPTION

#define THROWTEXTEXCEPTION CXU_THROWTEXTEXCEPTION
#define LOGTEXTEXCEPTION CXU_LOGTEXTEXCEPTION

#define THROWDATAEXCEPTION CXU_THROWDATAEXCEPTION
#define LOGDATAEXCEPTION CXU_LOGDATAEXCEPTION

#define THROWOSEXCEPTION CXU_THROWOSEXCEPTION
#define LOGOSEXCEPTION CXU_LOGOSEXCEPTION

#define THROWINTERFACEEXCEPTION CXU_THROWINTERFACEEXCEPTION
#define LOGINTERFACEEXCEPTION CXU_LOGINTERFACEEXCEPTION

#define THROWERREXCEPTION CXU_THROWERREXCEPTION
#define THROWERREXCEPTIONS CXU_THROWERREXCEPTIONS
#define THROWERREXCEPTIONHERE CXU_THROWERREXCEPTIONHERE
#define THROWERREXCEPTIONHERES CXU_THROWERREXCEPTIONHERES
#define LOGERREXCEPTION CXU_LOGERREXCEPTION
#define LOGERREXCEPTIONHERE CXU_LOGERREXCEPTIONHERE
#define LOGERREXCEPTIONHERES CXU_LOGERREXCEPTIONHERES
#define ERRCALL CXU_ERRCALL

#define ERRCALL CXU_ERRCALL
#define ERRCALLS CXU_ERRCALLS
#define RETERRCALL CXU_RETERRCALL
#define RETERRCALLS CXU_RETERRCALLS


#define ASSERT CXU_ASSERT
#define TRACE CXU_TRACE
#define TODO CXU_TODO

#define DECLARE_LIBINFO CXU_DECLARE_LIBINFO
#define IMPLEMENT_LIBINFO CXU_IMPLEMENT_LIBINFO

#define CHECK CXU_CHECK
#define CHECKPTR CXU_CHECKPTR
#define CHECKINT CXU_CHECKINT
#define CHECKSIZE CXU_CHECKSIZE
#define CHECKLONG CXU_CHECKLONG
#define CHECKCHAR CXU_CHECKCHAR
#define CHECKSTRING CXU_CHECKSTRING
#define CHECKREAL CXU_CHECKREAL
#define CHECKBOOL CXU_CHECKBOOL
#define TESTINFO CXU_TESTINFO

#define LOGGER CXU_LOGGER
#define MAINTHREAD CXU_MAINTHREAD
#define MAIN CXU_MAIN

#define DECLARE_SERIALIZABLE CXU_DECLARE_SERIALIZABLE

#define STACKARRAY CXU_STACKARRAY

#define CRTP_OV CXU_CRTP_OV
#define CRTP_CV CXU_CRTP_CV

#define CRTP_O CXU_CRTP_O 
#define CRTP_C CXU_CRTP_C


#endif

//.
