# YAL zeldan

PRODUCT := yoursoft

# uncomment one of the following
#TARGETS := app
#TARGETS := lib

# change for new versions
MAJVERS := 0
MINVERS := 0
RELEASE := 0

include zmk/defs.mk

# set as needed
#ZMK_CPPFLAGS := -DFOO -DBAR
#ZMK_CFLAGS := --myfantasticoption
#ZMK_LDLIBS := -lfoo -lbar

include zmk/build.mk


.PHONY: all
all: zmk_all

.PHONY: install
install: zmk_install

.PHONY: clean
clean: zmk_clean


	
#.
